/* eslint-disable no-magic-numbers */
module.exports = {
  layoutAndFormatting: {
    'array-bracket-newline': 0,
    'array-bracket-spacing': 0,
    'array-element-newline': 0,
    'arrow-parens': [
      2,
      'as-needed',
      {
        requireForBlockBody: false,
      },
    ],
    'arrow-spacing': 0,
    'block-spacing': 0,
    'brace-style': 0,
    'comma-dangle': 0,
    'comma-spacing': 0,
    'comma-style': 0,
    'computed-property-spacing': 0,
    'dot-location': 0,
    'eol-last': 0,
    'func-call-spacing': 0,
    'function-call-argument-newline': 0,
    'function-paren-newline': 0,
    'generator-star-spacing': 0,
    'implicit-arrow-linebreak': 0,
    'indent': 0,
    'jsx-quotes': 0,
    'key-spacing': 0,
    'keyword-spacing': 0,
    'line-comment-position': 0,
    'linebreak-style': 0,
    'lines-around-comment': 0,
    'lines-between-class-members': [
      2,
      'always',
      {
        exceptAfterSingleLine: true,
      },
    ],
    'max-len': [
      2,
      {
        code: 120,
        tabWidth: 2,
        comments: 120,
        ignorePattern: '',
        ignoreComments: false,
        ignoreTrailingComments: false,
        ignoreUrls: false,
        ignoreStrings: false,
        ignoreTemplateLiterals: false,
        ignoreRegExpLiterals: true,
      },
    ],
    'max-statements-per-line': [
      2,
      {
        max: 1,
      },
    ],
    'multiline-ternary': 0,
    'new-parens': 0,
    'no-mixed-spaces-and-tabs': 0,
    'no-multi-spaces': 0,
    'no-multiple-empty-lines': 0,
    'no-tabs': [
      2,
      {
        allowIndentationTabs: false,
      },
    ],
    'no-trailing-spaces': 0,
    'no-whitespace-before-property': 0,
    'nonblock-statement-body-position': 0,
    'object-curly-newline': 0,
    'object-curly-spacing': 0,
    'object-property-newline': 0,
    'operator-linebreak': 0,
    'padded-blocks': 0,
    'padding-line-between-statements': [
      2,
      { blankLine: 'always', prev: 'block-like', next: '*' },
      { blankLine: 'always', prev: '*', next: 'cjs-export' },
      { blankLine: 'always', prev: 'cjs-import', next: '*' },
      { blankLine: 'any', prev: 'cjs-import', next: 'cjs-import' },
      { blankLine: 'always', prev: '*', next: 'class' },
      { blankLine: 'always', prev: 'class', next: '*' },
      { blankLine: 'always', prev: 'const', next: '*' },
      { blankLine: 'any', prev: 'const', next: 'const' },
      { blankLine: 'always', prev: 'directive', next: '*' },
      { blankLine: 'never', prev: 'directive', next: 'directive' },
      { blankLine: 'always', prev: 'function', next: '*' },
      { blankLine: 'always', prev: '*', next: 'function' },
      { blankLine: 'always', prev: 'if', next: '*' },
      { blankLine: 'always', prev: 'import', next: '*' },
      { blankLine: 'any', prev: 'import', next: 'import' },
      { blankLine: 'always', prev: 'let', next: '*' },
      { blankLine: 'any', prev: 'let', next: 'let' },
      { blankLine: 'never', prev: 'let', next: 'if' },
      { blankLine: 'never', prev: 'let', next: 'while' },
      { blankLine: 'never', prev: 'let', next: 'do' },
      { blankLine: 'never', prev: 'let', next: 'try' },
      { blankLine: 'always', prev: '*', next: 'return' },
      { blankLine: 'never', prev: 'block-like', next: 'return' },
      { blankLine: 'always', prev: '*', next: 'throw' },
      { blankLine: 'never', prev: 'block-like', next: 'throw' },
    ],
    'quotes': 0,
    'rest-spread-spacing': 0,
    'semi': 0,
    'semi-spacing': 0,
    'semi-style': 0,
    'space-before-blocks': 0,
    'space-before-function-paren': 0,
    'space-in-parens': 0,
    'space-infix-ops': 0,
    'space-unary-ops': 0,
    'switch-colon-spacing': 0,
    'template-curly-spacing': 0,
    'template-tag-spacing': 0,
    'unicode-bom': [
      2,
      'never',
    ],
    'wrap-iife': 0,
    'wrap-regex': 0,
    'yield-star-spacing': 0,
  },
}
